"""empty message

Revision ID: 05286f031502
Revises: 075ef7b7f465
Create Date: 2020-01-14 18:05:47.004372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05286f031502'
down_revision = '075ef7b7f465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('test')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
